const state = { lang: 'pl', view: 'site', section: 'overview', selectedPatient: null };
const text = {
  pl: {
    nav: ['O mnie', 'Usługi', 'Certyfikaty', 'Kontakt'], hero: 'Twoje ciało. Twoja droga do sprawności.', intro: 'Rehabilitacja onkologiczna, fizjoterapia i dietetyka kliniczna — z uważnością na Twoje potrzeby.', call: 'Umów wizytę telefonicznie', crm: 'Otwórz CRM', support: 'Obszary wsparcia', about: 'Kilka słów o mnie', diet: 'Asystent jadłospisu', back: 'Wróć do strony', patients: 'Pacjenci', calendar: 'Kalendarz', plans: 'Plany dietetyczne', today: 'Dzisiaj', newPlan: 'Nowy plan', draft: 'Szkic do zatwierdzenia', sources: 'Źródła i zasady', create: 'Utwórz propozycję', name: 'Imię i nazwisko', goal: 'Cel', allergies: 'Alergie / wykluczenia', notes: 'Notatki Gosii', generate: 'Wygeneruj szkic', saved: 'Szkic zapisany do weryfikacji.'
  },
  en: {
    nav: ['About', 'Services', 'Certificates', 'Contact'], hero: 'Your body. Your path to recovery.', intro: 'Oncology rehabilitation, physiotherapy and clinical dietetics — thoughtfully tailored to your needs.', call: 'Book by phone', crm: 'Open CRM', support: 'Areas of support', about: 'A few words about me', diet: 'Meal-plan assistant', back: 'Back to website', patients: 'Patients', calendar: 'Calendar', plans: 'Meal plans', today: 'Today', newPlan: 'New plan', draft: 'Drafts to approve', sources: 'Sources and rules', create: 'Create proposal', name: 'Full name', goal: 'Goal', allergies: 'Allergies / exclusions', notes: 'Gosia notes', generate: 'Generate draft', saved: 'Draft saved for review.'
  }
};
const t = () => text[state.lang];
const patients = [
  { name: 'Anna Kowalska', type: 'Rehabilitacja onkologiczna', time: '08:00', color: 'rose' },
  { name: 'Maria Nowak', type: 'Dietetyka kliniczna', time: '10:30', color: 'green' },
  { name: 'Katarzyna Zielińska', type: 'Terapia przeciwobrzękowa', time: '15:30', color: 'gold' }
];
function site() { const c=t(); document.querySelector('#app').innerHTML=`<div class="shell"><header class="topbar"><div class="brand"><span class="brand-mark"></span>onkofizjo</div><nav class="nav">${c.nav.map(n=>`<a href="#">${n}</a>`).join('')}<button class="lang" data-action="lang">${state.lang==='pl'?'EN':'PL'}</button></nav><button class="menu">☰</button></header><main><section class="hero"><div class="hero-copy"><span class="eyebrow">onkofizjo · Małgorzata Papierz</span><h1>${c.hero}</h1><p>${c.intro}</p><div class="actions"><button class="btn btn-primary" data-action="phone">${c.call}</button><button class="btn btn-secondary" data-action="crm">${c.crm}</button></div></div><div class="hero-image" aria-label="Małgorzata Papierz"></div></section><section class="section"><div class="section-head"><h2>${c.about}</h2><p class="section-lead">Łączę doświadczenie fizjoterapeutki z rozwijającą się specjalizacją w dietetyce klinicznej. Każdy plan zaczyna się od rozmowy, uważnej oceny i wspólnego celu.</p></div></section><section class="section alt"><div class="section-head"><h2>${c.support}</h2><p class="section-lead">Wybierz obszar, w którym chcesz poczuć więcej pewności i sprawczości.</p></div><div class="cards"><article class="card accent"><h3>Rehabilitacja onkologiczna</h3><p>Wsparcie po mastektomii, rekonstrukcji, radioterapii i leczeniu onkologicznym.</p></article><article class="card"><h3>Terapia przeciwobrzękowa</h3><p>Drenaż limfatyczny, terapia blizny, bandażowanie i indywidualnie dobrane ćwiczenia.</p></article><article class="card"><h3>Dietetyka kliniczna</h3><p>Spersonalizowane zalecenia i jadłospisy dopasowane do życia, zdrowia i celów.</p></article></div></section></main><footer class="footer"><span>onkofizjo · rehabilitacja onkologiczna i dietetyka kliniczna</span><span>Polski / English</span></footer></div>`; bind(); }
function crm() { const c=t(); document.querySelector('#app').innerHTML=`<div class="crm-view"><header class="crm-header"><div class="brand"><span class="brand-mark"></span>onkofizjo CRM</div><button class="back" data-action="site">← ${c.back}</button></header><main class="crm-main"><div class="crm-title-row"><div><span class="eyebrow">${c.today} · 13 sierpnia</span><h2>${c.crm}</h2></div><button class="btn btn-primary" data-action="diet">${c.newPlan}</button></div><div class="crm-nav"><button class="${state.section==='overview'?'active':''}" data-section="overview">${c.calendar}</button><button class="${state.section==='patients'?'active':''}" data-section="patients">${c.patients}</button><button class="${state.section==='plans'?'active':''}" data-section="plans">${c.plans}</button><button class="${state.section==='sources'?'active':''}" data-section="sources">${c.sources}</button></div>${state.section==='overview'?overview(c):state.section==='patients'?patientList(c):state.section==='plans'?plans(c):sources(c)}</main></div>`; bind(); }
function overview(c) { return `<div class="crm-grid"><div class="metric"><span>${c.calendar}</span><strong>8</strong><small>${c.today}</small></div><div class="metric"><span>${c.patients}</span><strong>124</strong><small>+4 w tym miesiącu</small></div><div class="metric"><span>${c.draft}</span><strong>3</strong><small>${c.plans}</small></div><div class="metric"><span>Rozliczenie dnia</span><strong>1 240 zł</strong><small>3 płatności</small></div></div><div class="crm-content"><section class="panel"><div class="panel-head"><h3>${c.calendar}</h3><span>13.08.2026</span></div><div class="appointment-list">${patients.map(p=>`<button class="appointment" data-patient="${p.name}"><span class="time">${p.time}</span><span class="dot ${p.color}"></span><span><strong>${p.name}</strong><small>${p.type}</small></span><span>›</span></button>`).join('')}</div></section><aside class="panel assistant"><span class="eyebrow">AI · ${c.diet}</span><h3>${c.diet}</h3><p>Przygotuj propozycję na podstawie profilu pacjenta, alergii, preferencji i zatwierdzonych zasad Gosii.</p><button class="btn btn-primary" data-action="diet">${c.create}</button></aside></div>`; }
function patientList(c) { return `<section class="panel"><div class="panel-head"><h3>${c.patients}</h3><span>124</span></div>${patients.map(p=>`<button class="appointment" data-patient="${p.name}"><span class="dot ${p.color}"></span><span><strong>${p.name}</strong><small>${p.type} · ${p.time}</small></span><span>›</span></button>`).join('')}</section>`; }
function plans(c) { return `<section class="panel"><div class="panel-head"><h3>${c.plans}</h3><button class="btn btn-primary" data-action="diet">${c.newPlan}</button></div><div class="plan-row"><span class="dot green"></span><span><strong>Maria Nowak</strong><small>Propozycja · dieta kliniczna · aktualizacja dziś</small></span><b>${c.draft}</b></div><div class="plan-row"><span class="dot gold"></span><span><strong>Anna Kowalska</strong><small>Plan zatwierdzony · rehabilitacja i żywienie</small></span><b>Gotowy</b></div></section>`; }
function sources(c) { return `<section class="panel source-panel"><span class="eyebrow">RAG · ${c.sources}</span><h3>Każda sugestia musi być wyjaśnialna.</h3><p>Źródła naukowe, reguły zatwierdzone przez Gosię i notatki zawodowe będą przechowywane oddzielnie, wersjonowane i cytowane przy każdej propozycji.</p><div class="source-tags"><span>Reguły Gosii</span><span>Guidelines</span><span>Open access studies</span><span>Historia pacjenta</span></div></section>`; }
function diet() { const c=t(); document.querySelector('#app').innerHTML=`<div class="crm-view"><header class="crm-header"><div class="brand"><span class="brand-mark"></span>onkofizjo CRM</div><button class="back" data-action="crm">← ${c.back}</button></header><main class="crm-main"><span class="eyebrow">AI · ${c.diet}</span><h2>${c.diet}</h2><p class="section-lead">Szkic jest propozycją. Gosia zatwierdza każdy plan przed przekazaniem pacjentowi.</p><form class="diet-form" id="diet-form"><label>${c.name}<input name="name" placeholder="Maria Nowak" required></label><label>${c.goal}<input name="goal" placeholder="np. poprawa regularności posiłków" required></label><label>${c.allergies}<input name="allergies" placeholder="np. brak / orzechy / laktoza"></label><label>${c.notes}<textarea name="notes" placeholder="Preferencje, rytm dnia, reguły indywidualne"></textarea></label><button class="btn btn-primary" type="submit">${c.generate}</button><p id="diet-result" class="form-result" hidden>${c.saved}</p></form></main></div>`; document.querySelector('#diet-form').onsubmit=e=>{e.preventDefault();document.querySelector('#diet-result').hidden=false;}; }
function bind(){document.querySelectorAll('[data-action="lang"]').forEach(x=>x.onclick=()=>{state.lang=state.lang==='pl'?'en':'pl';state.view==='site'?site():crm();});document.querySelectorAll('[data-action="crm"]').forEach(x=>x.onclick=()=>{state.view='crm';crm();});document.querySelectorAll('[data-action="site"]').forEach(x=>x.onclick=()=>{state.view='site';site();});document.querySelectorAll('[data-action="diet"]').forEach(x=>x.onclick=()=>{state.view='diet';diet();});document.querySelectorAll('[data-section]').forEach(x=>x.onclick=()=>{state.section=x.dataset.section;crm();});document.querySelectorAll('[data-patient]').forEach(x=>x.onclick=()=>{state.selectedPatient=x.dataset.patient;state.view='diet';diet();});document.querySelectorAll('[data-action="phone"]').forEach(x=>x.onclick=()=>alert(state.lang==='pl'?'Zadzwoń bezpośrednio do Gosii, aby umówić wizytę.':'Call Gosia directly to book an appointment.'));}
site();
